# Placement Intelligence Platform

## Project Overview

The Placement Intelligence Platform (PIP) is an ML-powered placement prediction and recommendation system designed to simulate a real-world campus placement process. It combines database management, analytics, machine learning, recommendation systems, and interactive visualization to help students assess placement readiness and identify suitable companies.

## Objectives

- Generate realistic company data
- Populate CompanyRoles table
- Define role-specific technical skills
- Define company eligibility criteria
- Generate realistic student profiles
- Assign technical skills to students
- Populate placement records
- Store all generated data in MySQL

## Tech Stack

- Python
- MySQL
- Pandas
- NumPy
- Faker
- mysql-connector-python
- Jupyter Notebook

## Workflow

```text
Generate Companies
        │
        ▼
Generate Company Roles
        │
        ▼
Generate Role Skills
        │
        ▼
Generate Eligibility
        │
        ▼
Generate Students
        │
        ▼
Assign Student Skills
        │
        ▼
Generate Placements
        │
        ▼
Insert into MySQL Database
```

## Why Generate Synthetic Data?

Real placement datasets containing student information, company requirements, salaries, and placement outcomes are generally confidential.

To overcome this limitation, this project generates a synthetic dataset that mimics real campus placement patterns while preserving realistic relationships between students, companies, skills, and eligibility criteria.

The generated dataset is designed to resemble the placement ecosystem at NIT Durgapur and supports the development of machine learning models and recommendation systems.

## Data Generation Strategy

The dataset generation process follows these principles:

- Different branches possess different technical skills.
- Different companies recruit for different job roles.
- Every job role requires a unique set of technical skills.
- Companies define branch eligibility and minimum CGPA requirements.
- Student profiles are generated using realistic academic distributions.
- Placement decisions depend on multiple factors rather than random assignment.

## Database Tables Populated

This notebook generates synthetic data and populates all database tables required for the Placement Intelligence Platform.

### Master (Reference) Tables

These tables store static reference data that is used throughout the platform.

- Branches
- Roles
- Skills

---

### Relationship (Junction) Tables

These tables establish many-to-many relationships between entities and support recommendation, eligibility checking, and skill mapping.

- CompanyRoles
- RoleSkills
- StudentSkills
- CompanyEligibility

---

### Transactional Tables

These tables store dynamic operational data generated during the placement process.

- Students
- Companies
- Placements

## Dataset Design

The generated synthetic placement dataset contains:

* **49 Companies**
* **36 Job Roles**
* **92 Technical & Soft Skills**
* **8 Engineering Branches**
* **750 Student Profiles**
* **215 Company–Role Mappings**
* **185 Role–Skill Mappings**
* **373 Company Eligibility Records**
* **5,245 Student Skill Records**
* **354 Placement Records**

The dataset is relationally designed using MySQL with appropriate primary keys, foreign keys, and many-to-many relationship tables. Student placements are generated based on multiple factors, including branch eligibility, minimum CGPA requirements, preferred job role, coding performance, aptitude, communication skills, internships, projects, and technical skills, resulting in a realistic synthetic placement dataset suitable for SQL analysis, exploratory data analysis (EDA), machine learning, and recommendation systems.

## Data Distribution

The dataset is designed to resemble real campus placements.

Examples:

- CSE students generally possess stronger software development skills.
- EE and ECE students possess embedded systems and electrical engineering skills.
- Mechanical students possess CAD and manufacturing skills.
- Biotechnology students possess research-oriented skills.
- Core companies primarily recruit core branches.
- Product-based companies recruit students with stronger technical profiles.

## Machine Learning Features

The generated dataset is designed to support machine learning models for campus placement prediction and recommendation systems.

The primary features include:

* CGPA
* Coding Score
* DSA Solved
* Number of Projects
* Number of Internships
* Communication Score
* Aptitude Score
* Branch
* Preferred Role
* Technical Skills
* Active Backlogs
* Gender

In addition to student-related features, the dataset also incorporates company eligibility constraints such as branch eligibility, minimum CGPA requirements, and role-specific skill requirements through relational tables.

### Target Variable

* **Placement Status** (Placed / Not Placed)

This dataset can be used for various machine learning tasks, including:

* Placement Prediction (Binary Classification)
* Company Recommendation
* Job Role Recommendation
* Skill Gap Analysis
* Student Profiling
* Placement Analytics
* Feature Importance Analysis

## Import Required Libraries

In [324]:
import pandas as pd
import numpy as np
import random
import mysql.connector
from datetime import date

### A fixed random seed was used during synthetic data generation to ensure reproducibility of the generated dataset.

In [ ]:
random.seed(42)
np.random.seed(42)

## Connecting Python to MySQL Database

In [325]:
import os

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password=os.getenv("MYSQL_PASSWORD"),
    database="placement_platform"
)

cursor = conn.cursor()

print("✅ Connected Successfully!")

✅ Connected Successfully!

## MASTER TABLES

## Step 1 - Company Dataset

In [326]:
companies = [

    # Software / Product Companies
    {"CompanyName":"Microsoft","Category":"Category-3","Industry":"Software","Headquarters":"USA"},
    {"CompanyName":"Adobe","Category":"Category-3","Industry":"Software","Headquarters":"USA"},
    {"CompanyName":"Apple","Category":"Category-3","Industry":"Consumer Electronics","Headquarters":"USA"},
    {"CompanyName":"Oracle","Category":"Category-3","Industry":"Enterprise Software","Headquarters":"USA"},
    {"CompanyName":"Cisco","Category":"Category-3","Industry":"Networking","Headquarters":"USA"},
    {"CompanyName":"NVIDIA","Category":"Category-3","Industry":"Semiconductor","Headquarters":"USA"},
    {"CompanyName":"Intel","Category":"Category-3","Industry":"Semiconductor","Headquarters":"USA"},
    {"CompanyName":"Qualcomm","Category":"Category-3","Industry":"Semiconductor","Headquarters":"USA"},
    {"CompanyName":"Texas Instruments","Category":"Category-3","Industry":"Semiconductor","Headquarters":"USA"},
    {"CompanyName":"Samsung","Category":"Category-3","Industry":"Electronics","Headquarters":"South Korea"},
    {"CompanyName":"MediaTek","Category":"Category-3","Industry":"Semiconductor","Headquarters":"Taiwan"},
    {"CompanyName":"NXP","Category":"Category-3","Industry":"Semiconductor","Headquarters":"Netherlands"},

    # Finance
    {"CompanyName":"JP Morgan Chase","Category":"Category-3","Industry":"Banking","Headquarters":"USA"},
    {"CompanyName":"Wells Fargo","Category":"Category-2","Industry":"Banking","Headquarters":"USA"},
    {"CompanyName":"BNY Mellon","Category":"Category-2","Industry":"Banking","Headquarters":"USA"},
    {"CompanyName":"ICICI Bank","Category":"Category-2","Industry":"Banking","Headquarters":"India"},
    {"CompanyName":"NatWest","Category":"Category-2","Industry":"Banking","Headquarters":"United Kingdom"},
    {"CompanyName":"HSBC","Category":"Category-2","Industry":"Banking","Headquarters":"United Kingdom"},
    {"CompanyName":"PayPal","Category":"Category-3","Industry":"FinTech","Headquarters":"USA"},
    {"CompanyName":"Visa","Category":"Category-3","Industry":"FinTech","Headquarters":"USA"},

    # IT Services & Consulting
    {"CompanyName":"TCS","Category":"Category-2","Industry":"IT Services","Headquarters":"India"},
    {"CompanyName":"Infosys","Category":"Category-2","Industry":"IT Services","Headquarters":"India"},
    {"CompanyName":"Accenture","Category":"Category-2","Industry":"Consulting","Headquarters":"Ireland"},
    {"CompanyName":"Deloitte","Category":"Category-2","Industry":"Consulting","Headquarters":"USA"},
    {"CompanyName":"PwC","Category":"Category-2","Industry":"Consulting","Headquarters":"United Kingdom"},
    {"CompanyName":"Capgemini","Category":"Category-2","Industry":"IT Services","Headquarters":"France"},
    {"CompanyName":"EXL","Category":"Category-2","Industry":"Analytics","Headquarters":"USA"},
    {"CompanyName":"ZS Associates","Category":"Category-2","Industry":"Consulting","Headquarters":"USA"},
    {"CompanyName":"Sigmoid","Category":"Category-2","Industry":"Analytics","Headquarters":"India"},
    {"CompanyName":"Tredence","Category":"Category-2","Industry":"Analytics","Headquarters":"India"},
    {"CompanyName":"Publicis Sapient","Category":"Category-2","Industry":"Consulting","Headquarters":"France"},
    {"CompanyName":"GreyB","Category":"Category-2","Industry":"Research & Consulting","Headquarters":"India"},

    # Core Engineering
    {"CompanyName":"Larsen & Toubro","Category":"Category-2","Industry":"Engineering","Headquarters":"India"},
    {"CompanyName":"Tata Steel","Category":"Category-2","Industry":"Steel","Headquarters":"India"},
    {"CompanyName":"JSW Steel","Category":"Category-2","Industry":"Steel","Headquarters":"India"},
    {"CompanyName":"Electrosteel","Category":"Category-2","Industry":"Steel","Headquarters":"India"},
    {"CompanyName":"Adani Group","Category":"Category-2","Industry":"Infrastructure","Headquarters":"India"},
    {"CompanyName":"Reliance Industries","Category":"Category-2","Industry":"Energy","Headquarters":"India"},
    {"CompanyName":"Bharat Petroleum","Category":"Category-2","Industry":"Oil & Gas","Headquarters":"India"},
    {"CompanyName":"Haldia Petrochemicals","Category":"Category-2","Industry":"Petrochemicals","Headquarters":"India"},
    {"CompanyName":"HMEL","Category":"Category-2","Industry":"Oil & Gas","Headquarters":"India"},
    {"CompanyName":"TVS Motors","Category":"Category-2","Industry":"Automobile","Headquarters":"India"},
    {"CompanyName":"Mahindra & Mahindra","Category":"Category-2","Industry":"Automobile","Headquarters":"India"},
    {"CompanyName":"Bajaj Auto","Category":"Category-2","Industry":"Automobile","Headquarters":"India"},
    {"CompanyName":"Bosch","Category":"Category-2","Industry":"Automobile","Headquarters":"Germany"},
    {"CompanyName":"Saint-Gobain","Category":"Category-2","Industry":"Manufacturing","Headquarters":"France"},
    {"CompanyName":"Vedanta","Category":"Category-2","Industry":"Mining","Headquarters":"India"},
    {"CompanyName":"Danieli India","Category":"Category-2","Industry":"Steel Equipment","Headquarters":"India"},
    {"CompanyName":"Hexagon","Category":"Category-2","Industry":"Engineering Software","Headquarters":"Sweden"}
]

companies_df = pd.DataFrame(companies)

print("Total Companies:", len(companies_df))

Total Companies: 49

## Insert Data into MySQL

In [327]:
insert_query = """
INSERT INTO Companies
(CompanyName, Category, Industry, Headquarters)
VALUES (%s, %s, %s, %s)
"""

cursor.execute("SELECT COUNT(*) FROM Companies")
count = cursor.fetchone()[0]

if count == 0:
    cursor.executemany(insert_query, companies_df.values.tolist())
    conn.commit()
    print(f"✅ {len(companies_df)} companies inserted successfully!")
else:
    print(f"⚠️ Companies table already contains {count} records. Skipping insertion.")

⚠️ Companies table already contains 49 records. Skipping insertion.

## Verify

In [328]:
companies_df.head(10)

         CompanyName    Category              Industry Headquarters
0          Microsoft  Category-3              Software          USA
1              Adobe  Category-3              Software          USA
2              Apple  Category-3  Consumer Electronics          USA
3             Oracle  Category-3   Enterprise Software          USA
4              Cisco  Category-3            Networking          USA
5             NVIDIA  Category-3         Semiconductor          USA
6              Intel  Category-3         Semiconductor          USA
7           Qualcomm  Category-3         Semiconductor          USA
8  Texas Instruments  Category-3         Semiconductor          USA
9            Samsung  Category-3           Electronics  South Korea

## Save Dataset

In [329]:
companies_df.to_csv("../dataset/companies.csv", index=False)

print("✅ companies.csv saved successfully!")

✅ companies.csv saved successfully!

In [330]:
companies_df.columns

Index(['CompanyName', 'Category', 'Industry', 'Headquarters'], dtype='str')

## Company Dictionary

In [331]:
companies_df = pd.read_sql(
    "SELECT * FROM Companies;",
    conn
)

companies_df.head()

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\2825439142.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  companies_df = pd.read_sql(

   CompanyID CompanyName    Category              Industry Headquarters
0          1   Microsoft  Category-3              Software          USA
1          2       Adobe  Category-3              Software          USA
2          3       Apple  Category-3  Consumer Electronics          USA
3          4      Oracle  Category-3   Enterprise Software          USA
4          5       Cisco  Category-3            Networking          USA

In [332]:
company_dict = dict(
    zip(companies_df["CompanyName"], companies_df["CompanyID"])
)

company_dict

{'Microsoft': 1,
 'Adobe': 2,
 'Apple': 3,
 'Oracle': 4,
 'Cisco': 5,
 'NVIDIA': 6,
 'Intel': 7,
 'Qualcomm': 8,
 'Texas Instruments': 9,
 'Samsung': 10,
 'MediaTek': 11,
 'NXP': 12,
 'JP Morgan Chase': 13,
 'Wells Fargo': 14,
 'BNY Mellon': 15,
 'ICICI Bank': 16,
 'NatWest': 17,
 'HSBC': 18,
 'PayPal': 19,
 'Visa': 20,
 'TCS': 21,
 'Infosys': 22,
 'Accenture': 23,
 'Deloitte': 24,
 'PwC': 25,
 'Capgemini': 26,
 'EXL': 27,
 'ZS Associates': 28,
 'Sigmoid': 29,
 'Tredence': 30,
 'Publicis Sapient': 31,
 'GreyB': 32,
 'Larsen & Toubro': 33,
 'Tata Steel': 34,
 'JSW Steel': 35,
 'Electrosteel': 36,
 'Adani Group': 37,
 'Reliance Industries': 38,
 'Bharat Petroleum': 39,
 'Haldia Petrochemicals': 40,
 'HMEL': 41,
 'TVS Motors': 42,
 'Mahindra & Mahindra': 43,
 'Bajaj Auto': 44,
 'Bosch': 45,
 'Saint-Gobain': 46,
 'Vedanta': 47,
 'Danieli India': 48,
 'Hexagon': 49}

## Step 2 - Roles Dataset

## Load Companies from MySQL

In [333]:
companies_df = pd.read_sql("SELECT * FROM Companies;", conn)

companies_df.head()

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\2450969300.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  companies_df = pd.read_sql("SELECT * FROM Companies;", conn)

   CompanyID CompanyName    Category              Industry Headquarters
0          1   Microsoft  Category-3              Software          USA
1          2       Adobe  Category-3              Software          USA
2          3       Apple  Category-3  Consumer Electronics          USA
3          4      Oracle  Category-3   Enterprise Software          USA
4          5       Cisco  Category-3            Networking          USA

## ROLES

In [334]:
roles = [

# ---------------- SOFTWARE ----------------

("Software Engineer","Software"),
("Backend Developer","Software"),
("Frontend Developer","Software"),
("Full Stack Developer","Software"),
("Machine Learning Engineer","Software"),
("Data Scientist","Software"),
("AI Engineer","Software"),
("DevOps Engineer","Software"),
("Cloud Engineer","Software"),
("Database Engineer","Software"),
("QA Engineer","Software"),

# ---------------- ANALYTICS ----------------

("Data Analyst","Analytics"),
("Business Analyst","Analytics"),
("BI Analyst","Analytics"),

# ---------------- SEMICONDUCTOR ----------------

("Embedded Engineer","Electronics"),
("Firmware Engineer","Electronics"),
("VLSI Engineer","Electronics"),
("Hardware Engineer","Electronics"),

# ---------------- CORE ----------------

("Mechanical Engineer","Core"),
("Electrical Engineer","Core"),
("Civil Engineer","Core"),
("Chemical Engineer","Core"),
("Metallurgical Engineer","Core"),
("Production Engineer","Core"),
("Process Engineer","Core"),
("Project Engineer","Core"),
("Design Engineer","Core"),

# ---------------- RESEARCH ----------------

("Research Associate","Research"),
("Research Engineer","Research"),

# ---------------- CONSULTING ----------------

("Technology Consultant","Consulting"),
("Consultant","Consulting"),

# ---------------- FINANCE ----------------

("Risk Analyst","Finance"),
("Quant Analyst","Finance"),

# ---------------- NETWORK ----------------

("Network Engineer","Networking"),
("Cybersecurity Engineer","Networking"),

# ---------------- MANAGEMENT ----------------

("Management Trainee","Management")

]

## Insert Data into MySQL

In [335]:
insert_query = """
INSERT INTO Roles (RoleName, RoleType)
VALUES (%s, %s)
"""

cursor.execute("SELECT COUNT(*) FROM Roles")
count = cursor.fetchone()[0]

if count == 0:
    cursor.executemany(insert_query, roles)
    conn.commit()
    print(f"✅ {len(roles)} roles inserted successfully!")
else:
    print(f"⚠️ Roles table already contains {count} records. Skipping insertion.")

⚠️ Roles table already contains 36 records. Skipping insertion.

## Verify

In [336]:
roles_df = pd.read_sql(
    "SELECT * FROM Roles;",
    conn
)

roles_df

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\3470201712.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  roles_df = pd.read_sql(

    RoleID                   RoleName     RoleType
0        1          Software Engineer     Software
1        2          Backend Developer     Software
2        3         Frontend Developer     Software
3        4       Full Stack Developer     Software
4        5  Machine Learning Engineer     Software
5        6             Data Scientist     Software
6        7                AI Engineer     Software
7        8            DevOps Engineer     Software
8        9             Cloud Engineer     Software
9       10          Database Engineer     Software
10      11                QA Engineer     Software
11      12               Data Analyst    Analytics
12      13           Business Analyst    Analytics
13      14                 BI Analyst    Analytics
14      15          Embedded Engineer  Electronics
15      16          Firmware Engineer  Electronics
16      17              VLSI Engineer  Electronics
17      18          Hardware Engineer  Electronics
18      19        Mechanical Engineer         Core
19      20        Electrical Engineer         Core
20      21             Civil Engineer         Core
21      22          Chemical Engineer         Core
22      23     Metallurgical Engineer         Core
23      24        Production Engineer         Core
24      25           Process Engineer         Core
25      26           Project Engineer         Core
26      27            Design Engineer         Core
27      28         Research Associate     Research
28      29          Research Engineer     Research
29      30      Technology Consultant   Consulting
30      31                 Consultant   Consulting
31      32               Risk Analyst      Finance
32      33              Quant Analyst      Finance
33      34           Network Engineer   Networking
34      35     Cybersecurity Engineer   Networking
35      36         Management Trainee   Management

## Save Dataset

In [337]:
roles_df.to_csv("../dataset/roles.csv", index=False)

print("✅ roles.csv saved successfully!")

✅ roles.csv saved successfully!

## Role Dictionary

In [338]:
role_dict = dict(zip(roles_df["RoleName"], roles_df["RoleID"]))

role_dict

{'Software Engineer': 1,
 'Backend Developer': 2,
 'Frontend Developer': 3,
 'Full Stack Developer': 4,
 'Machine Learning Engineer': 5,
 'Data Scientist': 6,
 'AI Engineer': 7,
 'DevOps Engineer': 8,
 'Cloud Engineer': 9,
 'Database Engineer': 10,
 'QA Engineer': 11,
 'Data Analyst': 12,
 'Business Analyst': 13,
 'BI Analyst': 14,
 'Embedded Engineer': 15,
 'Firmware Engineer': 16,
 'VLSI Engineer': 17,
 'Hardware Engineer': 18,
 'Mechanical Engineer': 19,
 'Electrical Engineer': 20,
 'Civil Engineer': 21,
 'Chemical Engineer': 22,
 'Metallurgical Engineer': 23,
 'Production Engineer': 24,
 'Process Engineer': 25,
 'Project Engineer': 26,
 'Design Engineer': 27,
 'Research Associate': 28,
 'Research Engineer': 29,
 'Technology Consultant': 30,
 'Consultant': 31,
 'Risk Analyst': 32,
 'Quant Analyst': 33,
 'Network Engineer': 34,
 'Cybersecurity Engineer': 35,
 'Management Trainee': 36}

## Step 3 - Skills Dataset

## Skills List

In [339]:
skills = [

# =========================
# Programming
# =========================

("Python","Programming",3),
("Java","Programming",3),
("C","Programming",2),
("C++","Programming",4),
("JavaScript","Programming",3),
("SQL","Database",2),
("Git","Programming",2),
("GitHub","Programming",2),
("Object Oriented Programming","Programming",3),
("Data Structures & Algorithms","Programming",5),

# =========================
# Web Development
# =========================

("HTML","Web Development",1),
("CSS","Web Development",1),
("Bootstrap","Web Development",2),
("React","Web Development",4),
("Node.js","Web Development",4),
("Express.js","Web Development",4),
("REST APIs","Web Development",3),

# =========================
# Database
# =========================

("MySQL","Database",2),
("MongoDB","Database",3),
("Database Design","Database",3),
("SQL Optimization","Database",4),

# =========================
# Data Science / AI
# =========================

("Pandas","Data Science",2),
("NumPy","Data Science",2),
("Scikit-Learn","Data Science",3),
("TensorFlow","Data Science",5),
("PyTorch","Data Science",5),
("Machine Learning","Data Science",5),
("Deep Learning","Data Science",5),
("Natural Language Processing","Data Science",5),
("Computer Vision","Data Science",5),
("Data Visualization","Data Science",3),
("Feature Engineering","Data Science",4),
("Model Evaluation","Data Science",4),

# =========================
# Cloud & DevOps
# =========================

("AWS","Cloud",4),
("Azure","Cloud",4),
("Google Cloud","Cloud",4),
("Docker","Cloud",3),
("Kubernetes","Cloud",5),
("Linux","Cloud",3),
("CI/CD","Cloud",4),

# =========================
# Cybersecurity
# =========================

("Computer Networks","Networking",3),
("Cyber Security","Networking",4),
("Network Security","Networking",4),
("Ethical Hacking","Networking",5),
("Cryptography","Networking",5),

# =========================
# Electronics
# =========================

("Embedded Systems","Electronics",4),
("Microcontrollers","Electronics",4),
("PCB Design","Electronics",4),
("Digital Electronics","Electronics",3),
("Analog Electronics","Electronics",3),
("VLSI","Electronics",5),
("Verilog","Electronics",5),
("FPGA","Electronics",5),
("Signal Processing","Electronics",4),

# =========================
# Electrical Engineering
# =========================

("Power Systems","Electrical",4),
("Control Systems","Electrical",4),
("Electrical Machines","Electrical",4),
("MATLAB","Electrical",3),
("PLC","Electrical",4),

# =========================
# Mechanical Engineering
# =========================

("CAD","Mechanical",3),
("SolidWorks","Mechanical",4),
("AutoCAD","Mechanical",3),
("CATIA","Mechanical",4),
("ANSYS","Mechanical",5),
("GD&T","Mechanical",4),
("Thermodynamics","Mechanical",4),
("Manufacturing Processes","Mechanical",3),

# =========================
# Civil Engineering
# =========================

("Structural Design","Civil",4),
("Surveying","Civil",3),
("STAAD Pro","Civil",5),
("ETABS","Civil",5),
("Construction Management","Civil",3),

# =========================
# Chemical Engineering
# =========================

("Process Design","Chemical",4),
("Process Simulation","Chemical",5),
("Heat Transfer","Chemical",4),
("Mass Transfer","Chemical",4),
("Chemical Reaction Engineering","Chemical",5),

# =========================
# Metallurgy
# =========================

("Material Science","Metallurgy",4),
("Heat Treatment","Metallurgy",4),
("Failure Analysis","Metallurgy",5),

# =========================
# Biotechnology
# =========================

("PCR","Biotechnology",4),
("Cell Culture","Biotechnology",5),
("Bioinformatics","Biotechnology",5),
("Genetics","Biotechnology",4),
("Molecular Biology","Biotechnology",5),

# =========================
# Soft Skills
# =========================

("Communication","Soft Skills",1),
("Leadership","Soft Skills",2),
("Teamwork","Soft Skills",1),
("Problem Solving","Soft Skills",2),
("Critical Thinking","Soft Skills",2),
("Presentation Skills","Soft Skills",2),
("Time Management","Soft Skills",1)

]

## DataFrame

In [340]:
skills_df = pd.DataFrame(
    skills,
    columns=[
        "SkillName",
        "SkillCategory",
        "DifficultyWeight"
    ]
)

skills_df

              SkillName SkillCategory  DifficultyWeight
0                Python   Programming                 3
1                  Java   Programming                 3
2                     C   Programming                 2
3                   C++   Programming                 4
4            JavaScript   Programming                 3
..                  ...           ...               ...
87             Teamwork   Soft Skills                 1
88      Problem Solving   Soft Skills                 2
89    Critical Thinking   Soft Skills                 2
90  Presentation Skills   Soft Skills                 2
91      Time Management   Soft Skills                 1

[92 rows x 3 columns]

## Save Dataset

In [341]:
skills_df.to_csv("../dataset/skills.csv", index=False)

print("✅ skills.csv saved successfully!")

✅ skills.csv saved successfully!

## Insert into MySQL

In [342]:
insert_query = """
INSERT INTO Skills
(SkillName, SkillCategory, DifficultyWeight)
VALUES (%s, %s, %s)
"""

cursor.execute("SELECT COUNT(*) FROM Skills")
count = cursor.fetchone()[0]

if count == 0:
    cursor.executemany(insert_query, skills)
    conn.commit()
    print(f"✅ {len(skills)} skills inserted successfully!")
else:
    print(f"⚠️ Skills table already contains {count} records. Skipping insertion.")

⚠️ Skills table already contains 92 records. Skipping insertion.

## Verify

In [343]:
skills_df = pd.read_sql(
    "SELECT * FROM Skills;",
    conn
)

skills_df.tail(15)

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\452561548.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  skills_df = pd.read_sql(

    SkillID            SkillName  SkillCategory  DifficultyWeight
77       78     Material Science     Metallurgy                 4
78       79       Heat Treatment     Metallurgy                 4
79       80     Failure Analysis     Metallurgy                 5
80       81                  PCR  Biotechnology                 4
81       82         Cell Culture  Biotechnology                 5
82       83       Bioinformatics  Biotechnology                 5
83       84             Genetics  Biotechnology                 4
84       85    Molecular Biology  Biotechnology                 5
85       86        Communication    Soft Skills                 1
86       87           Leadership    Soft Skills                 2
87       88             Teamwork    Soft Skills                 1
88       89      Problem Solving    Soft Skills                 2
89       90    Critical Thinking    Soft Skills                 2
90       91  Presentation Skills    Soft Skills                 2
91       92      Time Management    Soft Skills                 1

## Dictionary

In [344]:
skill_dict = dict(
    zip(
        skills_df["SkillName"],
        skills_df["SkillID"]
    )
)

skill_dict

{'Python': 1,
 'Java': 2,
 'C': 3,
 'C++': 4,
 'JavaScript': 5,
 'SQL': 6,
 'Git': 7,
 'GitHub': 8,
 'Object Oriented Programming': 9,
 'Data Structures & Algorithms': 10,
 'HTML': 11,
 'CSS': 12,
 'Bootstrap': 13,
 'React': 14,
 'Node.js': 15,
 'Express.js': 16,
 'REST APIs': 17,
 'MySQL': 18,
 'MongoDB': 19,
 'Database Design': 20,
 'SQL Optimization': 21,
 'Pandas': 22,
 'NumPy': 23,
 'Scikit-Learn': 24,
 'TensorFlow': 25,
 'PyTorch': 26,
 'Machine Learning': 27,
 'Deep Learning': 28,
 'Natural Language Processing': 29,
 'Computer Vision': 30,
 'Data Visualization': 31,
 'Feature Engineering': 32,
 'Model Evaluation': 33,
 'AWS': 34,
 'Azure': 35,
 'Google Cloud': 36,
 'Docker': 37,
 'Kubernetes': 38,
 'Linux': 39,
 'CI/CD': 40,
 'Computer Networks': 41,
 'Cyber Security': 42,
 'Network Security': 43,
 'Ethical Hacking': 44,
 'Cryptography': 45,
 'Embedded Systems': 46,
 'Microcontrollers': 47,
 'PCB Design': 48,
 'Digital Electronics': 49,
 'Analog Electronics': 50,
 'VLSI': 51,
 'Verilog': 52,
 'FPGA': 53,
 'Signal Processing': 54,
 'Power Systems': 55,
 'Control Systems': 56,
 'Electrical Machines': 57,
 'MATLAB': 58,
 'PLC': 59,
 'CAD': 60,
 'SolidWorks': 61,
 'AutoCAD': 62,
 'CATIA': 63,
 'ANSYS': 64,
 'GD&T': 65,
 'Thermodynamics': 66,
 'Manufacturing Processes': 67,
 'Structural Design': 68,
 'Surveying': 69,
 'STAAD Pro': 70,
 'ETABS': 71,
 'Construction Management': 72,
 'Process Design': 73,
 'Process Simulation': 74,
 'Heat Transfer': 75,
 'Mass Transfer': 76,
 'Chemical Reaction Engineering': 77,
 'Material Science': 78,
 'Heat Treatment': 79,
 'Failure Analysis': 80,
 'PCR': 81,
 'Cell Culture': 82,
 'Bioinformatics': 83,
 'Genetics': 84,
 'Molecular Biology': 85,
 'Communication': 86,
 'Leadership': 87,
 'Teamwork': 88,
 'Problem Solving': 89,
 'Critical Thinking': 90,
 'Presentation Skills': 91,
 'Time Management': 92}

## Step 4 - Branches Dataset

## Branch List

In [345]:
branches = [

("BT","Biotechnology","Research"),

("MME","Metallurgy & Materials Engineering","Core"),

("CHE","Chemical Engineering","Core"),

("CE","Civil Engineering","Core"),

("ME","Mechanical Engineering","Core"),

("EE","Electrical Engineering","Core"),

("ECE","Electronics & Communication Engineering","Core+Non-Core"),

("CSE","Computer Science & Engineering","Non-Core")

]

## DataFrame

In [346]:
branches_df = pd.DataFrame(
    branches,
    columns=[
        "BranchCode",
        "BranchName",
        "BranchType"
    ]
)

branches_df

  BranchCode                               BranchName     BranchType
0         BT                            Biotechnology       Research
1        MME       Metallurgy & Materials Engineering           Core
2        CHE                     Chemical Engineering           Core
3         CE                        Civil Engineering           Core
4         ME                   Mechanical Engineering           Core
5         EE                   Electrical Engineering           Core
6        ECE  Electronics & Communication Engineering  Core+Non-Core
7        CSE           Computer Science & Engineering       Non-Core

## Save Dataset

In [347]:
branches_df.to_csv(
    "../dataset/branches.csv",
    index=False
)

print("✅ branches.csv saved successfully!")

✅ branches.csv saved successfully!

## Insert into MySQL

In [348]:
insert_query = """
INSERT INTO Branches
(BranchCode, BranchName, BranchType)
VALUES (%s,%s,%s)
"""

cursor.execute("SELECT COUNT(*) FROM Branches")
count = cursor.fetchone()[0]

if count == 0:
    cursor.executemany(insert_query, branches)
    conn.commit()
    print(f"✅ {len(branches)} branches inserted successfully!")
else:
    print(f"⚠️ Branches table already contains {count} records. Skipping insertion.")

⚠️ Branches table already contains 8 records. Skipping insertion.

## Verify

In [349]:
branches_df = pd.read_sql(
    "SELECT * FROM Branches;",
    conn
)

branches_df

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\1557097561.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  branches_df = pd.read_sql(

,BranchID,BranchCode,BranchName,BranchType
0,1,CSE,Computer Science and Engineering,Non-Core
1,2,ECE,Electronics and Communication Engineering,Core+Non-Core
2,3,EE,Electrical Engineering,Core
3,4,ME,Mechanical Engineering,Core
4,5,CE,Civil Engineering,Core
5,6,CHE,Chemical Engineering,Core
6,7,MME,Metallurgical and Materials Engineering,Core
7,8,BT,Biotechnology,Research

## Dictionary

In [350]:
branch_dict = dict(
    zip(
        branches_df["BranchCode"],
        branches_df["BranchID"]
    )
)

branch_dict

{'CSE': 1, 'ECE': 2, 'EE': 3, 'ME': 4, 'CE': 5, 'CHE': 6, 'MME': 7, 'BT': 8}

## RELATIONSHIP TABLES

## Step 5 - RoleSkills Relationship Dataset

## Mapping

In [351]:
role_skill_map = {

# ===========================
# SOFTWARE ROLES
# ===========================

"Software Engineer":[
    "Python",
    "Java",
    "C++",
    "SQL",
    "Git",
    "Object Oriented Programming",
    "Data Structures & Algorithms"
],

"Backend Developer":[
    "Python",
    "Java",
    "SQL",
    "Database Design",
    "REST APIs",
    "Git"
],

"Frontend Developer":[
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Git"
],

"Full Stack Developer":[
    "HTML",
    "CSS",
    "JavaScript",
    "React",
    "Node.js",
    "Express.js",
    "MySQL",
    "Git"
],

"Machine Learning Engineer":[
    "Python",
    "Machine Learning",
    "Scikit-Learn",
    "TensorFlow",
    "PyTorch",
    "NumPy",
    "Pandas",
    "SQL"
],

"Data Scientist":[
    "Python",
    "Pandas",
    "NumPy",
    "Machine Learning",
    "Data Visualization",
    "SQL",
    "Scikit-Learn"
],

"AI Engineer":[
    "Python",
    "Machine Learning",
    "Deep Learning",
    "TensorFlow",
    "PyTorch",
    "SQL",
    "Docker",
    "Git",
    "Linux"
],

"DevOps Engineer":[
    "Linux",
    "Docker",
    "AWS",
    "Kubernetes",
    "Git",
    "CI/CD"
],

"Cloud Engineer":[
    "AWS",
    "Azure",
    "Google Cloud",
    "Docker",
    "Linux"
],

"Database Engineer":[
    "MySQL",
    "MongoDB",
    "Database Design",
    "SQL",
    "SQL Optimization"
],

"QA Engineer":[
    "Python",
    "Java",
    "Git",
    "Problem Solving"
],

# ===========================
# ANALYTICS & AI ROLES
# ===========================

"Data Analyst":[
    "Python",
    "SQL",
    "Pandas",
    "NumPy",
    "Data Visualization",
    "Problem Solving",
    "Critical Thinking"
],

"Business Analyst":[
    "SQL",
    "Data Visualization",
    "Communication",
    "Critical Thinking",
    "Presentation Skills"
],

"BI Analyst":[
    "SQL",
    "Data Visualization",
    "Communication",
    "Presentation Skills",
    "Critical Thinking"
],

"Research Associate":[
    "Python",
    "Bioinformatics",
    "Data Visualization",
    "Problem Solving",
    "Communication"
],

# ===========================
# ELECTRONICS & NETWORKING ROLES
# ===========================

"Embedded Engineer":[
    "Embedded Systems",
    "Microcontrollers",
    "Digital Electronics",
    "Analog Electronics",
    "PCB Design",
    "C",
    "Problem Solving"
],

"VLSI Engineer":[
    "VLSI",
    "Verilog",
    "Digital Electronics",
    "Signal Processing",
    "MATLAB"
],

"Network Engineer":[
    "Computer Networks",
    "Network Security",
    "Linux",
    "Cyber Security",
    "Problem Solving"
],

"Cybersecurity Engineer":[
    "Cyber Security",
    "Network Security",
    "Ethical Hacking",
    "Cryptography",
    "Linux",
    "Computer Networks"
],

# ===========================
# CORE ENGINEERING ROLES
# ===========================

"Mechanical Engineer":[
    "CAD",
    "SolidWorks",
    "ANSYS",
    "CATIA",
    "Thermodynamics",
    "Manufacturing Processes",
    "GD&T"
],

"Civil Engineer":[
    "AutoCAD",
    "STAAD Pro",
    "ETABS",
    "Structural Design",
    "Surveying",
    "Construction Management"
],

"Electrical Engineer":[
    "Power Systems",
    "Control Systems",
    "Electrical Machines",
    "MATLAB",
    "PLC"
],

"Chemical Engineer":[
    "Process Design",
    "Process Simulation",
    "Heat Transfer",
    "Mass Transfer",
    "Chemical Reaction Engineering"
],

"Metallurgical Engineer":[
    "Material Science",
    "Heat Treatment",
    "Failure Analysis",
    "Problem Solving"
],

"Research Engineer":[
    "PCR",
    "Cell Culture",
    "Bioinformatics",
    "Genetics",
    "Molecular Biology",
    "Problem Solving"
],

# ===========================
# BUSINESS & MANAGEMENT ROLES
# ===========================

"Management Trainee":[
    "Communication",
    "Leadership",
    "Teamwork",
    "Presentation Skills",
    "Critical Thinking",
    "Time Management"
],

# ===========================
# ADDITIONAL CORE & ELECTRONICS ROLES
# ===========================

"Firmware Engineer":[
    "C",
    "Embedded Systems",
    "Microcontrollers",
    "Digital Electronics",
    "Verilog",
    "Problem Solving"
],

"Hardware Engineer":[
    "Embedded Systems",
    "Digital Electronics",
    "Analog Electronics",
    "PCB Design",
    "Problem Solving"
],

"Production Engineer":[
    "Manufacturing Processes",
    "CAD",
    "SolidWorks",
    "GD&T",
    "Problem Solving"
],

"Process Engineer":[
    "Process Design",
    "Process Simulation",
    "Heat Transfer",
    "Mass Transfer",
    "Problem Solving"
],

"Project Engineer":[
    "Communication",
    "Leadership",
    "Presentation Skills",
    "Problem Solving",
    "Time Management"
],

"Design Engineer":[
    "CAD",
    "SolidWorks",
    "AutoCAD",
    "ANSYS",
    "GD&T"
]
}

## Convert to RoleSkills Dataset

In [352]:
missing = set()

for role, skills in role_skill_map.items():
    for skill in skills:
        if skill not in skill_dict:
            missing.add(skill)

if missing:
    print("❌ Missing Skills:")
    print(sorted(missing))
else:
    print("✅ All skills exist.")

✅ All skills exist.

In [353]:
missing_roles = set()

for role in role_skill_map.keys():
    if role not in role_dict:
        missing_roles.add(role)

if missing_roles:
    print("❌ Missing Roles:")
    print(sorted(missing_roles))
else:
    print("✅ All roles exist.")

✅ All roles exist.

In [354]:
role_skills = []

for role, skills_required in role_skill_map.items():

    role_id = role_dict[role]

    for skill in skills_required:

        skill_id = skill_dict[skill]

        role_skills.append(
            (
                role_id,
                skill_id
            )
        )

print(f"Total Role-Skill mappings : {len(role_skills)}")

Total Role-Skill mappings : 185

## DataFrame

In [355]:
role_skills_df = pd.DataFrame(
    role_skills,
    columns=[
        "RoleID",
        "SkillID"
    ]
)

role_skills_df

     RoleID  SkillID
0         1        1
1         1        2
2         1        4
3         1        6
4         1        7
..      ...      ...
180      27       60
181      27       61
182      27       62
183      27       64
184      27       65

[185 rows x 2 columns]

## Save Dataset

In [356]:
role_skills_df.to_csv(
    "../dataset/role_skills.csv",
    index=False
)

print("✅ role_skills.csv saved successfully!")

✅ role_skills.csv saved successfully!

## Insert into MySQL

In [357]:
insert_query = """
INSERT INTO RoleSkills
(RoleID, SkillID)
VALUES (%s,%s)
"""

cursor.execute("SELECT COUNT(*) FROM RoleSkills")
count = cursor.fetchone()[0]

if count == 0:
    cursor.executemany(insert_query, role_skills)
    conn.commit()
    print(f"✅ {len(role_skills)} mappings inserted successfully!")
else:
    print(f"⚠️ RoleSkills already contains {count} records. Skipping insertion.")

⚠️ RoleSkills already contains 185 records. Skipping insertion.

## Verify

In [358]:
role_skills_df = pd.read_sql(
    "SELECT * FROM RoleSkills;",
    conn
)

role_skills_df

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\4030462577.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  role_skills_df = pd.read_sql(

     RoleID  SkillID
0         1        1
1         2        1
2         5        1
3         6        1
4         7        1
..      ...      ...
180      14       91
181      26       91
182      36       91
183      26       92
184      36       92

[185 rows x 2 columns]

## Step 6 - CompanyRoles Relationship Dataset

## Mapping

In [359]:
company_role_map = {

# ==========================
# SOFTWARE / IT
# ==========================

"Microsoft":[
    "Software Engineer",
    "Backend Developer",
    "Frontend Developer",
    "Full Stack Developer",
    "AI Engineer",
    "Cloud Engineer",
    "DevOps Engineer",
    "Data Scientist",
    "QA Engineer"
],

"Adobe":[
    "Software Engineer",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Machine Learning Engineer",
    "QA Engineer"
],

"Apple":[
    "Software Engineer",
    "Embedded Engineer",
    "Firmware Engineer",
    "Hardware Engineer"
],

"Oracle":[
    "Software Engineer",
    "Backend Developer",
    "Cloud Engineer",
    "Database Engineer",
    "QA Engineer"
],

"Cisco":[
    "Network Engineer",
    "Cybersecurity Engineer",
    "Software Engineer",
    "Embedded Engineer"
],

# ==========================
# SEMICONDUCTOR
# ==========================

"NVIDIA":[
    "AI Engineer",
    "Machine Learning Engineer",
    "Embedded Engineer",
    "Hardware Engineer",
    "VLSI Engineer"
],

"Intel":[
    "Embedded Engineer",
    "Hardware Engineer",
    "VLSI Engineer",
    "Firmware Engineer"
],

"Qualcomm":[
    "Embedded Engineer",
    "Firmware Engineer",
    "VLSI Engineer",
    "Hardware Engineer"
],

"Texas Instruments":[
    "Embedded Engineer",
    "VLSI Engineer",
    "Hardware Engineer"
],

"Samsung":[
    "Software Engineer",
    "Embedded Engineer",
    "Hardware Engineer",
    "VLSI Engineer"
],

"MediaTek":[
    "Embedded Engineer",
    "Firmware Engineer",
    "VLSI Engineer"
],

"NXP":[
    "Embedded Engineer",
    "Firmware Engineer",
    "Hardware Engineer"
],

# ==========================
# BANKING & FINTECH
# ==========================

"JP Morgan Chase":[
    "Software Engineer",
    "Backend Developer",
    "Data Analyst",
    "Business Analyst",
    "Risk Analyst",
    "Quant Analyst",
    "Cloud Engineer"
],

"Wells Fargo":[
    "Software Engineer",
    "Backend Developer",
    "Business Analyst",
    "Data Analyst",
    "Risk Analyst"
],

"BNY Mellon":[
    "Software Engineer",
    "Backend Developer",
    "Business Analyst",
    "Cloud Engineer"
],

"ICICI Bank":[
    "Software Engineer",
    "Business Analyst",
    "Data Analyst",
    "Risk Analyst"
],

"NatWest":[
    "Software Engineer",
    "Backend Developer",
    "Business Analyst",
    "Data Analyst"
],

"HSBC":[
    "Software Engineer",
    "Backend Developer",
    "Business Analyst",
    "Risk Analyst"
],

"PayPal":[
    "Software Engineer",
    "Backend Developer",
    "Full Stack Developer",
    "Cloud Engineer",
    "Data Scientist"
],

"Visa":[
    "Software Engineer",
    "Backend Developer",
    "Cloud Engineer",
    "Data Scientist"
],


# ==========================
# IT SERVICES
# ==========================

"TCS":[
    "Software Engineer",
    "Backend Developer",
    "Frontend Developer",
    "Full Stack Developer",
    "Data Analyst",
    "QA Engineer"
],

"Infosys":[
    "Software Engineer",
    "Backend Developer",
    "Frontend Developer",
    "Full Stack Developer",
    "Cloud Engineer",
    "QA Engineer"
],

"Capgemini":[
    "Software Engineer",
    "Backend Developer",
    "Frontend Developer",
    "QA Engineer",
    "Cloud Engineer"
],


# ==========================
# CONSULTING
# ==========================

"Accenture":[
    "Software Engineer",
    "Data Analyst",
    "Business Analyst",
    "Technology Consultant",
    "Consultant",
    "Cloud Engineer"
],

"Deloitte":[
    "Business Analyst",
    "Technology Consultant",
    "Consultant",
    "Risk Analyst",
    "Data Analyst"
],

"PwC":[
    "Business Analyst",
    "Technology Consultant",
    "Consultant",
    "Risk Analyst"
],

"ZS Associates":[
    "Business Analyst",
    "Data Analyst",
    "BI Analyst",
    "Data Scientist"
],

"Publicis Sapient":[
    "Software Engineer",
    "Full Stack Developer",
    "Technology Consultant",
    "Business Analyst"
],

"GreyB":[
    "Research Associate",
    "Research Engineer",
    "Business Analyst"
],

# ==========================
# ANALYTICS
# ==========================

"EXL":[
    "Data Analyst",
    "Business Analyst",
    "BI Analyst",
    "Data Scientist"
],

"Sigmoid":[
    "Data Scientist",
    "Machine Learning Engineer",
    "Data Analyst",
    "BI Analyst"
],

"Tredence":[
    "Data Scientist",
    "Machine Learning Engineer",
    "Data Analyst",
    "Business Analyst"
],

# ==========================
# ENGINEERING & INFRASTRUCTURE
# ==========================

"Larsen & Toubro":[
    "Mechanical Engineer",
    "Electrical Engineer",
    "Civil Engineer",
    "Project Engineer",
    "Design Engineer"
],

"Adani Group":[
    "Electrical Engineer",
    "Mechanical Engineer",
    "Civil Engineer",
    "Project Engineer"
],

"Hexagon":[
    "Software Engineer",
    "Mechanical Engineer",
    "Design Engineer",
    "Data Analyst"
],


# ==========================
# STEEL & METALLURGY
# ==========================

"Tata Steel":[
    "Metallurgical Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Production Engineer",
    "Process Engineer"
],

"JSW Steel":[
    "Metallurgical Engineer",
    "Mechanical Engineer",
    "Production Engineer",
    "Process Engineer"
],

"Electrosteel":[
    "Metallurgical Engineer",
    "Mechanical Engineer",
    "Production Engineer"
],

"Vedanta":[
    "Metallurgical Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Production Engineer"
],

"Danieli India":[
    "Mechanical Engineer",
    "Electrical Engineer",
    "Design Engineer",
    "Project Engineer"
],


# ==========================
# OIL & GAS / CHEMICAL
# ==========================

"Reliance Industries":[
    "Chemical Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Process Engineer",
    "Project Engineer"
],

"Bharat Petroleum":[
    "Chemical Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Process Engineer"
],

"Haldia Petrochemicals":[
    "Chemical Engineer",
    "Process Engineer",
    "Mechanical Engineer"
],

"HMEL":[
    "Chemical Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Process Engineer"
],


# ==========================
# AUTOMOBILE
# ==========================

"TVS Motors":[
    "Mechanical Engineer",
    "Production Engineer",
    "Design Engineer",
    "Electrical Engineer"
],

"Mahindra & Mahindra":[
    "Mechanical Engineer",
    "Production Engineer",
    "Design Engineer",
    "Electrical Engineer"
],

"Bajaj Auto":[
    "Mechanical Engineer",
    "Production Engineer",
    "Design Engineer"
],

"Bosch":[
    "Embedded Engineer",
    "Mechanical Engineer",
    "Electrical Engineer",
    "Design Engineer",
    "Firmware Engineer"
],


# ==========================
# MANUFACTURING
# ==========================

"Saint-Gobain":[
    "Mechanical Engineer",
    "Chemical Engineer",
    "Production Engineer",
    "Process Engineer"
]
}

In [360]:
missing_companies = set()
missing_roles = set()

for company, roles in company_role_map.items():

    if company not in company_dict:
        missing_companies.add(company)

    for role in roles:
        if role not in role_dict:
            missing_roles.add(role)

print("=" * 50)

if missing_companies:
    print("❌ Missing Companies:", sorted(missing_companies))
else:
    print("✅ All companies exist.")

print()

if missing_roles:
    print("❌ Missing Roles:", sorted(missing_roles))
else:
    print("✅ All roles exist.")

print("=" * 50)

==================================================
✅ All companies exist.

✅ All roles exist.
==================================================

In [361]:
company_roles = []

for company, roles in company_role_map.items():

    company_id = company_dict[company]

    for role in roles:

        role_id = role_dict[role]

        company_roles.append(
            (company_id, role_id)
        )

print(f"Total Company-Role mappings : {len(company_roles)}")

Total Company-Role mappings : 215

## Dataframe

In [362]:
company_roles_df = pd.DataFrame(
    company_roles,
    columns=[
        "CompanyID",
        "RoleID"
    ]
)

company_roles_df

     CompanyID  RoleID
0            1       1
1            1       2
2            1       3
3            1       4
4            1       7
..         ...     ...
210         45      16
211         46      19
212         46      22
213         46      24
214         46      25

[215 rows x 2 columns]

## Save Dataset

In [363]:
company_roles_df.to_csv(
    "../dataset/company_roles.csv",
    index=False
)

print("✅ company_roles.csv saved successfully!")

✅ company_roles.csv saved successfully!

## Insert into MySQL

In [364]:
insert_query = """
INSERT INTO CompanyRoles
(CompanyID, RoleID)
VALUES (%s, %s)
"""

cursor.execute("SELECT COUNT(*) FROM CompanyRoles")
count = cursor.fetchone()[0]

if count == 0:
    cursor.executemany(insert_query, company_roles)
    conn.commit()
    print(f"✅ {len(company_roles)} CompanyRoles inserted successfully!")
else:
    print(f"⚠️ CompanyRoles already contains {count} records. Skipping insertion.")

⚠️ CompanyRoles already contains 215 records. Skipping insertion.

## Verify

In [365]:
company_roles_df = pd.read_sql(
    "SELECT * FROM CompanyRoles;",
    conn
)

company_roles_df

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\1866600946.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  company_roles_df = pd.read_sql(

     CompanyRoleID  CompanyID  RoleID  Package
0               55          1       1    40.73
1               56          1       2    39.78
2               57          1       3    51.82
3               58          1       4    55.11
4               59          1       7    54.59
..             ...        ...     ...      ...
210            265         45      16    11.44
211            266         46      19    10.71
212            267         46      22    13.58
213            268         46      24    12.78
214            269         46      25    10.46

[215 rows x 4 columns]

## Step 7 - Package Generation

## Company Tiers

In [366]:
tier1 = [
    "Microsoft",
    "Apple",
    "NVIDIA",
    "Google",
    "Amazon",
    "Meta",
    "JP Morgan Chase",
    "Goldman Sachs"
]

tier2 = [
    "Adobe",
    "Oracle",
    "Cisco",
    "Intel",
    "Qualcomm",
    "Samsung",
    "Texas Instruments",
    "MediaTek",
    "NXP",
    "PayPal",
    "Visa",
    "Wells Fargo",
    "BNY Mellon",
    "HSBC",
    "NatWest",
    "ICICI Bank"
]

tier3 = [
    "Accenture",
    "Infosys",
    "TCS",
    "Deloitte",
    "PwC",
    "EY",
    "Capgemini",
    "Cognizant",
    "Wipro",
    "IBM",
    "LTIMindtree",
    "Tech Mahindra",
    "HCLTech",
    "ZS Associates"
]

## Role Multiplier

In [367]:
role_bonus = {

"AI Engineer":8,
"Machine Learning Engineer":7,
"Data Scientist":6,

"Software Engineer":5,
"Backend Developer":5,
"Frontend Developer":4,
"Full Stack Developer":6,
"Cloud Engineer":5,
"DevOps Engineer":5,

"Cybersecurity Engineer":5,
"Database Engineer":4,

"Embedded Engineer":4,
"Firmware Engineer":4,
"VLSI Engineer":6,
"Hardware Engineer":4,

"Business Analyst":2,
"BI Analyst":2,
"Data Analyst":3,
"Consultant":3,

"Mechanical Engineer":2,
"Civil Engineer":2,
"Electrical Engineer":3,
"Chemical Engineer":2,
"Production Engineer":2,
"Process Engineer":2,
"Project Engineer":2,
"Design Engineer":3,

"Research Engineer":3,
"Research Associate":2,

"Network Engineer":3,
"QA Engineer":2,
"Metallurgical Engineer":2,
"Management Trainee":1
}

## Base Salary

In [368]:
tier_ranges = {

1:(35,50),

2:(18,30),

3:(8,16),

4:(6,10)

}

## Lookup Dictionaries

In [369]:
company_lookup = dict(
    zip(companies_df["CompanyID"], companies_df["CompanyName"])
)

role_lookup = dict(
    zip(roles_df["RoleID"], roles_df["RoleName"])
)

category_lookup = dict(
    zip(companies_df["CompanyID"], companies_df["Category"])
)

## Generating Packages

In [370]:
packages = []

for _, row in company_roles_df.iterrows():

    company = company_lookup[row["CompanyID"]]
    role = role_lookup[row["RoleID"]]
    category = category_lookup[row["CompanyID"]]

    # Company Tier
    if company in tier1:
        low, high = tier_ranges[1]

    elif company in tier2:
        low, high = tier_ranges[2]

    elif company in tier3:
        low, high = tier_ranges[3]

    else:
        low, high = tier_ranges[4]

    
    package = random.uniform(low, high)

    
    package += role_bonus.get(role, 2)

    
    if category == "Category-1":
        package += 3

    elif category == "Category-2":
        package += 1.5

    
    package += random.uniform(-1, 1)

    packages.append(round(package, 2))

## Adding to DataFrame

In [371]:
company_roles_df["Package"] = packages

## Verify

In [372]:
company_roles_df.head()

   CompanyRoleID  CompanyID  RoleID  Package
0             55          1       1    52.86
1             56          1       2    53.11
2             57          1       3    52.65
3             58          1       4    51.05
4             59          1       7    42.74

## Updated CSV

In [373]:
company_roles_final = company_roles_df[
    [
        "CompanyRoleID",
        "CompanyID",
        "RoleID",
        "Package"
    ]
]

company_roles_final.to_csv(
    "../dataset/company_roles.csv",
    index=False
)

print("✅ company_roles.csv saved successfully!")

✅ company_roles.csv saved successfully!

## Updated SQL

In [374]:
update_query = """
UPDATE CompanyRoles
SET Package = %s
WHERE CompanyRoleID = %s
"""

update_data = list(
    zip(
        company_roles_final["Package"],
        company_roles_final["CompanyRoleID"]
    )
)

cursor.executemany(update_query, update_data)

conn.commit()

print(f"✅ Updated {cursor.rowcount} company role packages.")

✅ Updated 214 company role packages.

## Verify

In [375]:
verify_df = pd.read_sql(
    "SELECT * FROM CompanyRoles",
    conn
)

verify_df.head()

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\3461797580.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  verify_df = pd.read_sql(

   CompanyRoleID  CompanyID  RoleID  Package
0             55          1       1    52.86
1             56          1       2    53.11
2             57          1       3    52.65
3             58          1       4    51.05
4             59          1       7    42.74

## Step 8 - CompanyEligibility Relationship Dataset

## Load CompanyRoles

In [376]:
company_roles_db = pd.read_sql("""
SELECT *
FROM CompanyRoles;
""", conn)

company_roles_db.head()

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\3989720871.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  company_roles_db = pd.read_sql("""

   CompanyRoleID  CompanyID  RoleID  Package
0             55          1       1    52.86
1             56          1       2    53.11
2             57          1       3    52.65
3             58          1       4    51.05
4             59          1       7    42.74

### CompanyRole Lookup

This temporary lookup maps each `(CompanyID, RoleID)` pair to its corresponding `CompanyRoleID`.

In [377]:
company_role_lookup = {}

for _, row in company_roles_db.iterrows():

    company_role_lookup[
        (row["CompanyID"], row["RoleID"])
    ] = row["CompanyRoleID"]

print(f"✅ {len(company_role_lookup)} CompanyRole mappings loaded.")

✅ 215 CompanyRole mappings loaded.

## Verify

In [378]:
list(company_role_lookup.items())[:10]

[((np.float64(1.0), np.float64(1.0)), np.float64(55.0)),
 ((np.float64(1.0), np.float64(2.0)), np.float64(56.0)),
 ((np.float64(1.0), np.float64(3.0)), np.float64(57.0)),
 ((np.float64(1.0), np.float64(4.0)), np.float64(58.0)),
 ((np.float64(1.0), np.float64(7.0)), np.float64(59.0)),
 ((np.float64(1.0), np.float64(9.0)), np.float64(60.0)),
 ((np.float64(1.0), np.float64(8.0)), np.float64(61.0)),
 ((np.float64(1.0), np.float64(6.0)), np.float64(62.0)),
 ((np.float64(1.0), np.float64(11.0)), np.float64(63.0)),
 ((np.float64(2.0), np.float64(1.0)), np.float64(64.0))]

### Role Eligibility Rules

Each job role is assigned a set of eligible branches and a minimum CGPA.

In [379]:
role_eligibility_rules = {

    # ==========================
    # SOFTWARE
    # ==========================

    "Software Engineer":{
        "branches":["CSE","ECE"],
        "cgpa":8.0
    },

    "Backend Developer":{
        "branches":["CSE"],
        "cgpa":8.0
    },

    "Frontend Developer":{
        "branches":["CSE"],
        "cgpa":7.8
    },

    "Full Stack Developer":{
        "branches":["CSE"],
        "cgpa":8.0
    },

    "Machine Learning Engineer":{
        "branches":["CSE"],
        "cgpa":8.2
    },

    "Data Scientist":{
        "branches":["CSE"],
        "cgpa":8.2
    },

    "AI Engineer":{
        "branches":["CSE"],
        "cgpa":8.3
    },

    "Cloud Engineer":{
        "branches":["CSE","ECE"],
        "cgpa":7.8
    },

    "DevOps Engineer":{
        "branches":["CSE","ECE"],
        "cgpa":7.8
    },

    "Database Engineer":{
        "branches":["CSE"],
        "cgpa":7.8
    },

    "QA Engineer":{
        "branches":["CSE","ECE"],
        "cgpa":7.2
    },

    # ==========================
    # ANALYTICS
    # ==========================

    "Data Analyst":{
        "branches":["CSE","ECE"],
        "cgpa":7.5
    },

    "Business Analyst":{
        "branches":["CSE","ECE","EE"],
        "cgpa":7.2
    },

    "BI Analyst":{
        "branches":["CSE","ECE"],
        "cgpa":7.5
    },

    "Technology Consultant":{
        "branches":["CSE","ECE","EE"],
        "cgpa":7.2
    },

    "Consultant":{
        "branches":["CSE","ECE","EE"],
        "cgpa":7.0
    },

    "Risk Analyst":{
        "branches":["CSE","ECE"],
        "cgpa":7.5
    },

    "Quant Analyst":{
        "branches":["CSE","ECE"],
        "cgpa":8.2
    },

    # ==========================
    # ELECTRONICS
    # ==========================

    "Embedded Engineer":{
        "branches":["ECE","EE"],
        "cgpa":7.8
    },

    "Firmware Engineer":{
        "branches":["ECE","EE"],
        "cgpa":7.8
    },

    "Hardware Engineer":{
        "branches":["ECE","EE"],
        "cgpa":7.5
    },

    "VLSI Engineer":{
        "branches":["ECE"],
        "cgpa":8.0
    },

    "Network Engineer":{
        "branches":["ECE","CSE"],
        "cgpa":7.5
    },

    "Cybersecurity Engineer":{
        "branches":["CSE","ECE"],
        "cgpa":7.8
    },

    # ==========================
    # CORE
    # ==========================

    "Mechanical Engineer":{
        "branches":["ME"],
        "cgpa":7.0
    },

    "Electrical Engineer":{
        "branches":["EE"],
        "cgpa":7.0
    },

    "Civil Engineer":{
        "branches":["CE"],
        "cgpa":7.0
    },

    "Chemical Engineer":{
        "branches":["CHE"],
        "cgpa":7.0
    },

    "Metallurgical Engineer":{
        "branches":["MME"],
        "cgpa":7.0
    },

    "Production Engineer":{
        "branches":["ME","MME"],
        "cgpa":6.8
    },

    "Process Engineer":{
        "branches":["CHE","ME"],
        "cgpa":7.0
    },

    "Project Engineer":{
        "branches":["ME","CE","EE"],
        "cgpa":7.0
    },

    "Design Engineer":{
        "branches":["ME","CE"],
        "cgpa":7.0
    },

    # ==========================
    # RESEARCH
    # ==========================

    "Research Associate":{
        "branches":["BT","CSE"],
        "cgpa":7.5
    },

    "Research Engineer":{
        "branches":["BT","CSE","ECE"],
        "cgpa":7.5
    },

    "Management Trainee":{
        "branches":["CSE","ECE","EE","ME","CE","CHE","MME","BT"],
        "cgpa":6.5
    }
}

## Generating CompanyEligibility

In [380]:
company_eligibility = []

for _, row in company_roles_db.iterrows():

    company_role_id = row["CompanyRoleID"]
    role_id = row["RoleID"]

    # Get role name
    role_name = roles_df.loc[
        roles_df["RoleID"] == role_id,
        "RoleName"
    ].values[0]

    rule = role_eligibility_rules[role_name]

    for branch in rule["branches"]:

        company_eligibility.append(
            (
                company_role_id,
                branch_dict[branch],
                rule["cgpa"]
            )
        )

print(f"Total Company Eligibility mappings : {len(company_eligibility)}")

Total Company Eligibility mappings : 373

## DataFrame

In [381]:
company_eligibility_df = pd.DataFrame(
    company_eligibility,
    columns=[
        "CompanyRoleID",
        "BranchID",
        "MinimumCGPA"
    ]
)

company_eligibility_df.head()

   CompanyRoleID  BranchID  MinimumCGPA
0           55.0         1          8.0
1           55.0         2          8.0
2           56.0         1          8.0
3           57.0         1          7.8
4           58.0         1          8.0

## Save Dataset

In [382]:
company_eligibility_df.to_csv(
    "../dataset/company_eligibility.csv",
    index=False
)

print("✅ company_eligibility.csv saved successfully!")

✅ company_eligibility.csv saved successfully!

## Insert into MySQL

In [383]:
insert_query = """
INSERT INTO CompanyEligibility
(CompanyRoleID, BranchID, MinimumCGPA)
VALUES (%s, %s, %s)
"""

cursor.execute("SELECT COUNT(*) FROM CompanyEligibility")
count = cursor.fetchone()[0]

if count == 0:
    cursor.executemany(insert_query, company_eligibility)
    conn.commit()
    print(f"✅ {len(company_eligibility)} eligibility records inserted successfully!")
else:
    print(f"⚠️ CompanyEligibility already contains {count} records. Skipping insertion.")

⚠️ CompanyEligibility already contains 373 records. Skipping insertion.

## Verify

In [384]:
verify_df = pd.read_sql("""
SELECT
    c.CompanyName,
    r.RoleName,
    b.BranchCode,
    ce.MinimumCGPA
FROM CompanyEligibility ce

JOIN CompanyRoles cr
    ON ce.CompanyRoleID = cr.CompanyRoleID

JOIN Companies c
    ON cr.CompanyID = c.CompanyID

JOIN Roles r
    ON cr.RoleID = r.RoleID

JOIN Branches b
    ON ce.BranchID = b.BranchID

ORDER BY c.CompanyName, r.RoleName;
""", conn)

verify_df

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\1140397015.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  verify_df = pd.read_sql("""

       CompanyName          RoleName BranchCode  MinimumCGPA
0        Accenture  Business Analyst        CSE          7.2
1        Accenture  Business Analyst         EE          7.2
2        Accenture  Business Analyst        ECE          7.2
3        Accenture    Cloud Engineer        ECE          7.8
4        Accenture    Cloud Engineer        CSE          7.8
..             ...               ...        ...          ...
368  ZS Associates  Business Analyst        ECE          7.2
369  ZS Associates  Business Analyst        CSE          7.2
370  ZS Associates      Data Analyst        CSE          7.5
371  ZS Associates      Data Analyst        ECE          7.5
372  ZS Associates    Data Scientist        CSE          8.2

[373 rows x 4 columns]

## Step 7 - Students Dataset

### Branch to Preferred Role Mapping

Each academic branch is associated with a realistic set of preferred job roles.

In [385]:
branch_role_map = {

"CSE":[
    "Software Engineer",
    "Backend Developer",
    "Frontend Developer",
    "Full Stack Developer",
    "Machine Learning Engineer",
    "Data Scientist",
    "AI Engineer",
    "Cloud Engineer",
    "DevOps Engineer",
    "QA Engineer",
    "Database Engineer"
],

"ECE":[
    "Embedded Engineer",
    "Firmware Engineer",
    "Hardware Engineer",
    "VLSI Engineer",
    "Network Engineer",
    "Cybersecurity Engineer",
    "Software Engineer"
],

"EE":[
    "Electrical Engineer",
    "Embedded Engineer",
    "Project Engineer",
    "Hardware Engineer"
],

"ME":[
    "Mechanical Engineer",
    "Production Engineer",
    "Design Engineer",
    "Project Engineer"
],

"CE":[
    "Civil Engineer",
    "Project Engineer",
    "Design Engineer"
],

"CHE":[
    "Chemical Engineer",
    "Process Engineer"
],

"MME":[
    "Metallurgical Engineer",
    "Production Engineer"
],

"BT":[
    "Research Associate",
    "Research Engineer"
]
}

### Student Generation Parameters

The following parameters control the size and distribution of the generated student dataset.

In [386]:
random.seed(42)
np.random.seed(42)

NUM_STUDENTS = 750

## Branch Distribution

In [387]:
branch_distribution = {
    "CSE": 0.26,
    "ME": 0.20,
    "ECE": 0.15,
    "EE": 0.12,
    "CE": 0.10,
    "CHE": 0.08,
    "MME": 0.05,
    "BT": 0.04
}

## Gender Distribution

In [388]:
gender_distribution = {
    "Male": 0.72,
    "Female": 0.28
}

### Student Name Generation

A pool of common Indian first names and surnames is used to generate realistic student names.

In [389]:
male_first_names = [
    "Aarav","Aditya","Akash","Aman","Amit","Aniket","Arjun","Aryan",
    "Ayush","Deep","Harsh","Karan","Krishna","Manish","Mayank","Mohit",
    "Nikhil","Pranav","Rahul","Raj","Rohan","Rohit","Sahil","Sameer",
    "Sandeep","Shivam","Shubham","Siddharth","Suraj","Utkarsh",
    "Varun","Vikram","Vivek","Yash","Abhishek","Anirban","Soumyajit",
    "Sagnik","Ritwik","Anubhav","Tanmay","Debayan","Arnab","Sourav",
    "Subhajit","Sayan","Anurag","Kunal","Parth","Tanmoy"
]

female_first_names = [
    "Aditi","Ananya","Ankita","Aparna","Divya","Ishita","Kritika",
    "Megha","Neha","Nikita","Pooja","Priya","Riya","Shreya","Shruti",
    "Simran","Sneha","Sonali","Swati","Tanisha","Vaishnavi","Anushka",
    "Sanjana","Madhurima","Debarati","Rupsha","Moumita","Payel",
    "Swastika","Pallavi","Ritika","Nandini","Pragya","Sushmita",
    "Komal","Khushi","Muskan","Sakshi","Monalisa","Aishwarya"
]

last_names = [
    "Sharma","Verma","Gupta","Singh","Kumar","Das","Roy","Ghosh",
    "Chatterjee","Mukherjee","Banerjee","Bose","Dutta","Sen",
    "Saha","Pal","Paul","Mitra","Nandi","Chakraborty","Patel",
    "Yadav","Jha","Reddy","Naidu","Pillai","Nair","Mishra",
    "Pandey","Tripathi","Saxena","Agarwal","Jain","Bhardwaj",
    "Malhotra","Kapoor","Joshi","Kulkarni","Deshmukh","Mehta"
]

## Branch Prefixes

In [390]:
branch_prefix = {
    "CSE": "CS",
    "ECE": "EC",
    "EE": "EE",
    "ME": "ME",
    "CE": "CE",
    "CHE": "CH",
    "MME": "MM",
    "BT": "BT"
}

## Roll Number Counters

In [391]:
roll_counters = {
    "CSE": 1,
    "ECE": 1,
    "EE": 1,
    "ME": 1,
    "CE": 1,
    "CHE": 1,
    "MME": 1,
    "BT": 1
}

## Student Generation

In [392]:
students = []

for _ in range(NUM_STUDENTS):

    gender = np.random.choice(
        list(gender_distribution.keys()),
        p=list(gender_distribution.values())
    )


    if gender == "Male":
        first_name = random.choice(male_first_names)
    else:
        first_name = random.choice(female_first_names)

    last_name = random.choice(last_names)

    student_name = f"{first_name} {last_name}"

    branch = np.random.choice(
        list(branch_distribution.keys()),
        p=list(branch_distribution.values())
    )

    roll_no = (
        f"22"
        f"{branch_prefix[branch]}"
        f"{roll_counters[branch]:03d}"
    )

    roll_counters[branch] += 1

    preferred_role = random.choice(
        branch_role_map[branch]
    )

    students.append(
        (
            roll_no,
            student_name,
            gender,
            branch,
            preferred_role
        )
    )

print(f"Generated {len(students)} students.")

Generated 750 students.

## Verify

In [393]:
students_df = pd.DataFrame(
    students,
    columns=[
        "RollNumber",
        "StudentName",
        "Gender",
        "Branch",
        "PreferredRole"
    ]
)

students_df = students_df.sort_values("RollNumber").reset_index(drop=True)

students_df.head(10)

  RollNumber      StudentName  Gender Branch       PreferredRole
0    22BT001       Aditya Das    Male     BT  Research Associate
1    22BT002    Vikram Pillai    Male     BT   Research Engineer
2    22BT003       Amit Gupta    Male     BT   Research Engineer
3    22BT004      Sayan Yadav    Male     BT  Research Associate
4    22BT005     Sayan Mishra    Male     BT  Research Associate
5    22BT006     Ananya Ghosh  Female     BT   Research Engineer
6    22BT007      Ritwik Jain    Male     BT  Research Associate
7    22BT008  Manish Tripathi    Male     BT   Research Engineer
8    22BT009   Arjun Kulkarni    Male     BT  Research Associate
9    22BT010        Raj Joshi    Male     BT   Research Engineer

### Academic and Technical Attribute Generation

Each student is assigned academic and technical attributes based on their preferred job role.

## Role Performance Ranges

In [394]:
role_performance = {

    # Software Roles
    "Software Engineer": (7.5, 9.8, 75, 100),
    "Backend Developer": (7.5, 9.8, 80, 100),
    "Frontend Developer": (7.0, 9.5, 70, 95),
    "Full Stack Developer": (7.5, 9.8, 80, 100),
    "Machine Learning Engineer": (8.0, 9.9, 85, 100),
    "Data Scientist": (8.0, 9.9, 85, 100),
    "AI Engineer": (8.2, 9.9, 90, 100),
    "Cloud Engineer": (7.3, 9.6, 75, 95),
    "DevOps Engineer": (7.3, 9.6, 75, 95),
    "Database Engineer": (7.2, 9.5, 70, 95),
    "QA Engineer": (6.8, 9.3, 60, 90),

    # Analytics
    "Data Analyst": (7.0, 9.5, 60, 90),
    "Business Analyst": (6.8, 9.2, 50, 80),
    "BI Analyst": (7.0, 9.4, 60, 90),
    "Technology Consultant": (7.0, 9.3, 55, 85),
    "Consultant": (6.8, 9.2, 50, 80),
    "Risk Analyst": (7.2, 9.5, 60, 90),
    "Quant Analyst": (8.3, 9.9, 90, 100),

    # Electronics
    "Embedded Engineer": (7.2, 9.6, 65, 90),
    "Firmware Engineer": (7.3, 9.7, 70, 95),
    "Hardware Engineer": (7.0, 9.5, 60, 85),
    "VLSI Engineer": (8.0, 9.8, 80, 95),
    "Network Engineer": (7.0, 9.4, 60, 85),
    "Cybersecurity Engineer": (7.5, 9.8, 75, 95),

    # Core
    "Mechanical Engineer": (6.5, 9.2, 40, 70),
    "Electrical Engineer": (6.8, 9.3, 45, 75),
    "Civil Engineer": (6.5, 9.0, 40, 65),
    "Chemical Engineer": (6.5, 9.2, 40, 70),
    "Metallurgical Engineer": (6.5, 9.2, 40, 70),
    "Production Engineer": (6.5, 9.2, 45, 70),
    "Process Engineer": (6.8, 9.3, 45, 75),
    "Project Engineer": (6.8, 9.3, 45, 75),
    "Design Engineer": (6.8, 9.4, 50, 80),

    # Research
    "Research Associate": (7.5, 9.8, 60, 90),
    "Research Engineer": (7.8, 9.9, 70, 95),

    # Common
    "Management Trainee": (6.5, 9.0, 40, 70)
}

In [395]:
branch_ids = []
role_ids = []
cgpas = []
backlogs = []
internships = []
projects = []
coding_scores = []
communication_scores = []
emails = []
phones = []
dsa_solved = []
aptitude_scores = []
placement_status = []

for _, row in students_df.iterrows():

    role = row["PreferredRole"]
    branch = row["Branch"]

    
    branch_ids.append(branch_dict[branch])
    role_ids.append(role_dict[role])

    
    cgpa_min, cgpa_max, coding_min, coding_max = role_performance[role]

    
    cgpa = round(random.uniform(cgpa_min, cgpa_max), 2)
    cgpas.append(cgpa)

    
    coding = random.randint(coding_min, coding_max)
    coding_scores.append(coding)

    
    communication = random.randint(50, 100)
    communication_scores.append(communication)

    
    backlog = np.random.choice(
        [0, 1, 2, 3],
        p=[0.78, 0.15, 0.05, 0.02]
    )
    backlogs.append(backlog)

    
    internship = np.random.choice(
        [0, 1, 2, 3],
        p=[0.35, 0.40, 0.20, 0.05]
    )
    internships.append(internship)

    
    project = np.random.choice(
        [1, 2, 3, 4, 5, 6],
        p=[0.08, 0.20, 0.30, 0.22, 0.15, 0.05]
    )
    projects.append(project)
    
   
    name = row["StudentName"].lower().replace(" ", ".")
    emails.append(
    f"{name}.{row['RollNumber'].lower()}@nitdgp.ac.in"
)

    
    phones.append("9" + "".join(random.choices("0123456789", k=9)))

    if coding >= 90:
        dsa = random.randint(500, 800)
    elif coding >= 80:
        dsa = random.randint(300, 500)
    elif coding >= 70:
        dsa = random.randint(180, 300)
    elif coding >= 60:
        dsa = random.randint(80, 180)
    else:
        dsa = random.randint(20, 80)

    dsa_solved.append(dsa)

   
    aptitude_scores.append(random.randint(45, 100))

    
    placement_status.append("Not Placed")

In [396]:
students_df["BranchID"] = branch_ids
students_df["PreferredRoleID"] = role_ids
students_df["CGPA"] = cgpas
students_df["ActiveBacklogs"] = backlogs
students_df["InternshipCount"] = internships
students_df["ProjectCount"] = projects
students_df["CodingScore"] = coding_scores
students_df["CommunicationScore"] = communication_scores
students_df["Email"] = emails
students_df["Phone"] = phones
students_df["DSASolved"] = dsa_solved
students_df["AptitudeScore"] = aptitude_scores
students_df["PlacementStatus"] = placement_status

## Verify

In [397]:
students_df.head()

,RollNumber,StudentName,Gender,Branch,PreferredRole,BranchID,PreferredRoleID,CGPA,ActiveBacklogs,InternshipCount,ProjectCount,CodingScore,CommunicationScore,Email,Phone,DSASolved,AptitudeScore,PlacementStatus
0,22BT001,Aditya Das,Male,BT,Research Associate,8,28,7.84,0,1,1,81,65,aditya.das.22bt001@nitdgp.ac.in,9091031647,420,100,Not Placed
1,22BT002,Vikram Pillai,Male,BT,Research Engineer,8,29,9.58,0,1,3,93,53,vikram.pillai.22bt002@nitdgp.ac.in,9755943945,779,67,Not Placed
2,22BT003,Amit Gupta,Male,BT,Research Engineer,8,29,9.22,0,1,4,93,93,amit.gupta.22bt003@nitdgp.ac.in,9666125292,647,90,Not Placed
3,22BT004,Sayan Yadav,Male,BT,Research Associate,8,28,7.98,0,2,4,82,81,sayan.yadav.22bt004@nitdgp.ac.in,9339721639,388,94,Not Placed
4,22BT005,Sayan Mishra,Male,BT,Research Associate,8,28,9.35,2,0,2,69,52,sayan.mishra.22bt005@nitdgp.ac.in,9273424259,169,62,Not Placed

## Finalizing the Student Table

In [398]:
students_final_df = students_df[
    [
        "StudentName",
        "Gender",
        "Email",
        "Phone",
        "BranchID",
        "CGPA",
        "CodingScore",
        "DSASolved",
        "ProjectCount",
        "InternshipCount",
        "CommunicationScore",
        "AptitudeScore",
        "PreferredRoleID",
        "PlacementStatus"
    ]
].rename(
    columns={
        "StudentName": "Name",
        "ProjectCount": "Projects",
        "InternshipCount": "Internships"
    }
)

students_final_df.head()

,Name,Gender,Email,Phone,BranchID,CGPA,CodingScore,DSASolved,Projects,Internships,CommunicationScore,AptitudeScore,PreferredRoleID,PlacementStatus
0,Aditya Das,Male,aditya.das.22bt001@nitdgp.ac.in,9091031647,8,7.84,81,420,1,1,65,100,28,Not Placed
1,Vikram Pillai,Male,vikram.pillai.22bt002@nitdgp.ac.in,9755943945,8,9.58,93,779,3,1,53,67,29,Not Placed
2,Amit Gupta,Male,amit.gupta.22bt003@nitdgp.ac.in,9666125292,8,9.22,93,647,4,1,93,90,29,Not Placed
3,Sayan Yadav,Male,sayan.yadav.22bt004@nitdgp.ac.in,9339721639,8,7.98,82,388,4,2,81,94,28,Not Placed
4,Sayan Mishra,Male,sayan.mishra.22bt005@nitdgp.ac.in,9273424259,8,9.35,69,169,2,0,52,62,28,Not Placed

## Save Dataset

In [399]:
students_final = pd.read_sql(
    "SELECT * FROM Students",
    conn
)

students_final.to_csv(
    "../dataset/students.csv",   # or "dataset/students.csv" depending on your notebook location
    index=False
)

print("✅ students.csv updated from MySQL!")

✅ students.csv updated from MySQL!

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\2139854391.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  students_final = pd.read_sql(

## Insert into MySQL

In [400]:
insert_query = """
INSERT INTO Students
(
    Name,
    Gender,
    Email,
    Phone,
    BranchID,
    CGPA,
    CodingScore,
    DSASolved,
    Projects,
    Internships,
    CommunicationScore,
    AptitudeScore,
    PreferredRoleID,
    PlacementStatus
)
VALUES
(%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
"""

In [401]:
cursor.execute("SELECT COUNT(*) FROM Students")
count = cursor.fetchone()[0]

if count == 0:

    cursor.executemany(
        insert_query,
        students_final_df.values.tolist()
    )

    conn.commit()

    print(f"✅ {len(students_final_df)} students inserted successfully!")

else:
    print(f"⚠️ Students table already contains {count} records. Skipping insertion.")

✅ 750 students inserted successfully!

## Verify

In [402]:
students_db = pd.read_sql("""
SELECT *
FROM Students;
""", conn)

students_db.head()

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\3958694541.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  students_db = pd.read_sql("""

,StudentID,Name,Gender,Email,Phone,BranchID,CGPA,CodingScore,DSASolved,Projects,Internships,CommunicationScore,AptitudeScore,PreferredRoleID,PlacementStatus
0,3001,Aditya Das,Male,aditya.das.22bt001@nitdgp.ac.in,9091031647,8,7.84,81,420,1,1,65,100,28,Not Placed
1,3002,Vikram Pillai,Male,vikram.pillai.22bt002@nitdgp.ac.in,9755943945,8,9.58,93,779,3,1,53,67,29,Not Placed
2,3003,Amit Gupta,Male,amit.gupta.22bt003@nitdgp.ac.in,9666125292,8,9.22,93,647,4,1,93,90,29,Not Placed
3,3004,Sayan Yadav,Male,sayan.yadav.22bt004@nitdgp.ac.in,9339721639,8,7.98,82,388,4,2,81,94,28,Not Placed
4,3005,Sayan Mishra,Male,sayan.mishra.22bt005@nitdgp.ac.in,9273424259,8,9.35,69,169,2,0,52,62,28,Not Placed

## Step 8 - StudentSkills Dataset

## Reading RoleSkills from SQL

In [403]:
role_skills_db = pd.read_sql("""
SELECT *
FROM RoleSkills
""", conn)

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\498658342.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  role_skills_db = pd.read_sql("""

## RoleSkill Lookup

In [404]:
role_skill_dict = (
    role_skills_db
    .groupby("RoleID")["SkillID"]
    .apply(list)
    .to_dict()
)

role_skill_dict

{1: [1, 2, 4, 6, 7, 9, 10],
 2: [1, 2, 6, 7, 17, 20],
 3: [5, 7, 11, 12, 14],
 4: [5, 7, 11, 12, 14, 15, 16, 18],
 5: [1, 6, 22, 23, 24, 25, 26, 27],
 6: [1, 6, 22, 23, 24, 27, 31],
 7: [1, 6, 7, 25, 26, 27, 28, 37, 39],
 8: [7, 34, 37, 38, 39, 40],
 9: [34, 35, 36, 37, 39],
 10: [6, 18, 19, 20, 21],
 11: [1, 2, 7, 89],
 12: [1, 6, 22, 23, 31, 89, 90],
 13: [6, 31, 86, 90, 91],
 14: [6, 31, 86, 90, 91],
 15: [3, 46, 47, 48, 49, 50, 89],
 16: [3, 46, 47, 49, 52, 89],
 17: [49, 51, 52, 54, 58],
 18: [46, 48, 49, 50, 89],
 19: [60, 61, 63, 64, 65, 66, 67],
 20: [55, 56, 57, 58, 59],
 21: [62, 68, 69, 70, 71, 72],
 22: [73, 74, 75, 76, 77],
 23: [78, 79, 80, 89],
 24: [60, 61, 65, 67, 89],
 25: [73, 74, 75, 76, 89],
 26: [86, 87, 89, 91, 92],
 27: [60, 61, 62, 64, 65],
 28: [1, 31, 83, 86, 89],
 29: [81, 82, 83, 84, 85, 89],
 34: [39, 41, 42, 43, 89],
 35: [39, 41, 42, 43, 44, 45],
 36: [86, 87, 88, 90, 91, 92]}

## Reading Students from SQL

In [405]:
students_db = pd.read_sql("""
SELECT
    StudentID,
    PreferredRoleID
FROM Students
""", conn)

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\1484297120.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  students_db = pd.read_sql("""

## Generating StudentSkills

In [406]:
student_skills = []

all_skills = list(skill_dict.values())

for _, row in students_db.iterrows():

    student_id = row["StudentID"]
    role_id = row["PreferredRoleID"]

    required_skills = role_skill_dict[role_id]

    
    keep = random.randint(
        max(1, int(0.8 * len(required_skills))),
        len(required_skills)
    )

    student_required = random.sample(required_skills, keep)

    
    remaining = list(set(all_skills) - set(student_required))

    extra = random.sample(
        remaining,
        random.randint(1, 3)
    )

    final_skills = student_required + extra

    for skill in final_skills:
        student_skills.append((student_id, skill))

## Dataframe

In [407]:
student_skills_df = pd.DataFrame(
    student_skills,
    columns=["StudentID", "SkillID"]
)

student_skills_df = student_skills_df.drop_duplicates()

print("Total Student-Skill mappings:", len(student_skills_df))

student_skills_df.head()

Total Student-Skill mappings: 5245

   StudentID  SkillID
0       3192        4
1       3192        2
2       3192        7
3       3192        6
4       3192        9

## Validate Data

In [408]:
print("Duplicate mappings:", student_skills_df.duplicated().sum())
print("Unique Students:", student_skills_df["StudentID"].nunique())
print("Unique Skills:", student_skills_df["SkillID"].nunique())

Duplicate mappings: 0
Unique Students: 750
Unique Skills: 92

## Save Dataset

In [409]:
student_skills_df.to_csv(
    "../dataset/student_skills.csv",
    index=False
)

print("✅ student_skills.csv saved successfully!")

✅ student_skills.csv saved successfully!

## Insert into MySQL

In [410]:
insert_query = """
INSERT INTO StudentSkills
(
    StudentID,
    SkillID
)
VALUES
(%s, %s)
"""

cursor.execute("SELECT COUNT(*) FROM StudentSkills")
count = cursor.fetchone()[0]

if count == 0:

    cursor.executemany(
        insert_query,
        student_skills_df.values.tolist()
    )

    conn.commit()

    print(f"✅ {len(student_skills_df)} StudentSkills inserted successfully!")

else:
    print(f"⚠️ StudentSkills table already contains {count} records. Skipping insertion.")

✅ 5245 StudentSkills inserted successfully!

## Verify

In [411]:
student_skills_db = pd.read_sql("""
SELECT *
FROM StudentSkills;
""", conn)

print(f"Total StudentSkills : {len(student_skills_db)}")

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\2131820446.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  student_skills_db = pd.read_sql("""

Total StudentSkills : 5245

## Step 12 - Placements Dataset

## Reading Required Tables

In [412]:
students_db = pd.read_sql("""
SELECT *
FROM Students
""", conn)

company_roles_db = pd.read_sql("""
SELECT *
FROM CompanyRoles
""", conn)

company_eligibility_db = pd.read_sql("""
SELECT *
FROM CompanyEligibility
""", conn)

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\3241392119.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  students_db = pd.read_sql("""
C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\3241392119.py:6: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  company_roles_db = pd.read_sql("""
C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\3241392119.py:11: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  company_eligibility_db = pd.read_sql("""

## Eligibility Lookup

In [413]:
eligibility_dict = {}

for _, row in company_eligibility_db.iterrows():

    company_role = int(row["CompanyRoleID"])
    branch = int(row["BranchID"])
    cgpa = float(row["MinimumCGPA"])

    eligibility_dict.setdefault(company_role, []).append(
        (branch, cgpa)
    )

## CompanyRole Lookup by Preferred Role

In [414]:
role_company_dict = (
    company_roles_db
    .groupby("RoleID")["CompanyRoleID"]
    .apply(list)
    .to_dict()
)

## Merging Skill Count

In [415]:
skill_count_df = (
    student_skills_df
    .groupby("StudentID")
    .size()
    .reset_index(name="SkillCount")
)

students_db = students_db.merge(
    skill_count_df,
    on="StudentID",
    how="left"
)

students_db["SkillCount"] = (
    students_db["SkillCount"]
    .fillna(0)
    .astype(int)
)

students_db.head()

,StudentID,Name,Gender,Email,Phone,BranchID,CGPA,CodingScore,DSASolved,Projects,Internships,CommunicationScore,AptitudeScore,PreferredRoleID,PlacementStatus,SkillCount
0,3001,Aditya Das,Male,aditya.das.22bt001@nitdgp.ac.in,9091031647,8,7.84,81,420,1,1,65,100,28,Not Placed,6
1,3002,Vikram Pillai,Male,vikram.pillai.22bt002@nitdgp.ac.in,9755943945,8,9.58,93,779,3,1,53,67,29,Not Placed,9
2,3003,Amit Gupta,Male,amit.gupta.22bt003@nitdgp.ac.in,9666125292,8,9.22,93,647,4,1,93,90,29,Not Placed,8
3,3004,Sayan Yadav,Male,sayan.yadav.22bt004@nitdgp.ac.in,9339721639,8,7.98,82,388,4,2,81,94,28,Not Placed,5
4,3005,Sayan Mishra,Male,sayan.mishra.22bt005@nitdgp.ac.in,9273424259,8,9.35,69,169,2,0,52,62,28,Not Placed,8

## Placement Score Function

In [416]:
def calculate_score(student):

    score = (
        
    (student["CGPA"] / 10) * 27 +
    (student["CodingScore"] / 100) * 22 +
    (student["AptitudeScore"] / 100) * 14 +
    (student["CommunicationScore"] / 100) * 10 +
    (min(student["DSASolved"], 500) / 500) * 10 +
    (min(student["Projects"], 5) / 5) * 5 +
    (min(student["Internships"], 2) / 2) * 4 +
    (min(student["SkillCount"], 12) / 12) * 3
    
    )

    return round(score, 2)

In [417]:
calculate_score(students_db.iloc[0])

np.float64(72.39)

## Placement Probability Function

In [418]:
def placement_probability(score):

    if score >= 90:
        return 0.98
    elif score >= 80:
        return 0.90
    elif score >= 70:
        return 0.75
    elif score >= 60:
        return 0.55
    elif score >= 50:
        return 0.35
    else:
        return 0.15

In [419]:
placement_probability(82)

0.9

## Placement Filling Loop

In [420]:
placements = []
placed_student_ids = []

for _, student in students_db.iterrows():

    student_id = student["StudentID"]
    role_id = student["PreferredRoleID"]
    branch_id = student["BranchID"]
    cgpa = student["CGPA"]

    
    company_roles = role_company_dict.get(role_id, [])

    eligible_company_roles = []

    
    for company_role in company_roles:

        rules = eligibility_dict.get(company_role, [])

        for eligible_branch, cutoff in rules:

            if branch_id == eligible_branch and cgpa >= cutoff:
                eligible_company_roles.append(company_role)
                break

    
    if not eligible_company_roles:
        continue

    
    score = calculate_score(student)

    
    probability = placement_probability(score)

    
    if random.random() < probability:

        selected_company_role = random.choice(eligible_company_roles)

        placements.append(
            (
                student_id,
                selected_company_role,
                "Placed",
                date.today()
            )
        )

        placed_student_ids.append(student_id)

In [421]:
print(len(placements))

354

## DataFrame

In [422]:
placements_df = pd.DataFrame(
    placements,
    columns=[
        "StudentID",
        "CompanyRoleID",
        "PlacementStatus",
        "PlacementDate"
    ]
)

placements_df.head()

   StudentID  CompanyRoleID PlacementStatus PlacementDate
0       3002            187          Placed    2026-07-04
1       3003            187          Placed    2026-07-04
2       3006            187          Placed    2026-07-04
3       3008            187          Placed    2026-07-04
4       3009            186          Placed    2026-07-04

## Validate

In [423]:
print("Total Placements :", len(placements_df))
print("Unique Students :", placements_df["StudentID"].nunique())
print("Duplicate Students :", placements_df["StudentID"].duplicated().sum())

Total Placements : 354
Unique Students : 354
Duplicate Students : 0

## Update Placed Students

In [424]:
update_query = """
UPDATE Students
SET PlacementStatus = 'Placed'
WHERE StudentID = %s
"""

cursor.executemany(
    update_query,
    [(sid,) for sid in placed_student_ids]
)

conn.commit()

## Save Dataset

In [425]:
placements_df.to_csv(
    "../dataset/placements.csv",
    index=False
)

print("✅ placements.csv saved successfully!")

✅ placements.csv saved successfully!

## Insert into MySQL

In [426]:
insert_query = """
INSERT INTO Placements
(
    StudentID,
    CompanyRoleID,
    PlacementStatus,
    PlacementDate
)
VALUES
(%s, %s, %s, %s)
"""

cursor.execute("SELECT COUNT(*) FROM Placements")
count = cursor.fetchone()[0]

if count == 0:

    cursor.executemany(
        insert_query,
        placements_df.values.tolist()
    )

    conn.commit()

    print(f"✅ {len(placements_df)} placements inserted successfully!")

else:
    print(f"⚠️ Placements table already contains {count} records. Skipping insertion.")

✅ 354 placements inserted successfully!

## Verify

In [427]:
placements_db = pd.read_sql("""
SELECT *
FROM Placements
""", conn)

print("Total Placements :", len(placements_db))

placements_db.head()

Total Placements : 354

C:\Users\kabit\AppData\Local\Temp\ipykernel_14196\1082696451.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  placements_db = pd.read_sql("""

   PlacementID  StudentID  CompanyRoleID PlacementStatus PlacementDate
0         1958       3002            187          Placed    2026-07-04
1         1959       3003            187          Placed    2026-07-04
2         1960       3006            187          Placed    2026-07-04
3         1961       3008            187          Placed    2026-07-04
4         1962       3009            186          Placed    2026-07-04

## FINAL VERIFICATION AND CALCULATIONS

In [428]:
tables = [
    "Branches",
    "Roles",
    "Skills",
    "Companies",
    "RoleSkills",
    "CompanyRoles",
    "CompanyEligibility",
    "Students",
    "StudentSkills",
    "Placements"
]

for table in tables:
    cursor.execute(f"SELECT COUNT(*) FROM {table}")
    print(f"{table:<20} {cursor.fetchone()[0]}")

Branches             8
Roles                36
Skills               92
Companies            49
RoleSkills           185
CompanyRoles         215
CompanyEligibility   373
Students             750
StudentSkills        5245
Placements           354

# Summary

Completed Tasks

- Generated realistic placement dataset
- Populated MySQL database
- Created relationships among companies, students, skills, and placements
- Prepared dataset for machine learning

Next Steps

- Perform Exploratory Data Analysis (EDA)
- Build Placement Prediction Model
- Develop Recommendation Engine
- Create Skill Gap Analysis
- Build Interactive Dashboard using Gradio

# Learning Outcomes

During this notebook, I learned:

- Synthetic data generation
- Database population using Python
- MySQL integration with Python
- Data engineering concepts
- Building datasets for machine learning
- Maintaining referential integrity while generating relational data